#include <string.h>
#include <iostream>

#include <switch.h>
using namespace std;
int main(int argc, char* argv[])
{


    

    while(appletMainLoop())
    {
    consoleInit(NULL);
        //Scan all the inputs. This should be done once for each frame

    int A = 0;
    int C = 0;
        hidScanInput();

        //hidKeysDown returns information about which buttons have been just pressed (and they weren't in the previous frame)
        u32 kDown = hidKeysDown(CONTROLLER_P1_AUTO);

    cout << "YAFSM sWoTCH\n";
    cout << "version 0.6.0\n";
    for(C = 0; C >= 0; C = C+5){

        hidScanInput();

        //hidKeysDown returns information about which buttons have been just pressed (and they weren't in the previous frame)
        u32 kDown = hidKeysDown(CONTROLLER_P1_AUTO);

    if (C == 1800)
{
    cout << "if it dont work then go for a\n";
    cout << "henati break and try again lator\n";
    cout << "if u too scared for pokegomz pres +\n";
}
    if (C == 3600) cout << "DOWNLAOD FLIES OF POKEGOMZ!!\n";
    if (C == 5400) cout << "DOWNOLA COMPETE!!\n";
    if (C == 7200)
{
    cout << "bribing gam freck to\n";
    cout << "pathc valted pokegomz intoo sord and sheld..\n";
}
    if (C == 9600) cout << "DOANLOAD AND INSTAL FRII LGPE SWSH NSP\n";
    if (C == 10200) cout << "instalnig sord and sheld nashunal dechs mod \nand unofishul transfur tol to lunch usin \naplicashun mod in hebrew lawnchair\nuntil th briberii cunvinsez gam freck to #BrinBakNashunalDechs..\n";
    if (C == 10800)
{
    cout << "now downloa and isntal xy\n";
    cout << "oras sm usum port for swithc\n";
}
    if (C == 11400)
{
    cout << "doanola and instal dpp hgss\n";
    cout << "bw b2w2 port for swotch\n";
}
    if (C == 13200) cout << "doanlaod and isntall rse frlg port for swith\n";
    if (C == 15000) cout << "doanloa and instal gsc rby port for swoth\n";
    if (C == 15000) cout << "jus mak sur u don kil ur pokegomz or u bric!!\n";
    if (C == 18600) cout << "runing clongo exploit..\n";
    if (C == 20400) cout << "dongrodi to 1.0.0\n";
    if (C == 22200) cout << "pathcing flies of pokegomz..\n";
    if (C == 23400) cout << "sicc now generat new systume imag..\n";
    if (C == 25200) cout << "systume imag genrat nowa flash ontoo emptii brian\n";
    if (C == 26100) cout << "doo sam ting with recuvurii and fei partishuns\n";
    if (C == 27000) cout << "nowe update from dum atmosfer to raynx\n";
    if (C == 27900) cout << "now u hav raynx becaus atmosfer succ 4-bite bik\n";
    if (C == 28800) cout << "donola 2TB reshiram\n";
    if (C == 29700) cout << "flash by-os form u..\n";
    if (C == 30600) cout << "arguin in #meta abot rul 11..\n";
    if (C == 31500) cout << "OH NO HECK U GOT FRIKKEN BAN BY MASUDA!!\n";
    if (C == 32400) cout << "runin sube too mellzbaxfrend (ur such a hackers)\n";
    if (C == 33300) cout << "u got aron ban my dud!!\n";
    if (C == 34200) cout << "cunvirtin flies of pokegomz\n";
    if (C == 35100) cout << "now imparti flies of pokegomz..\n";
    if (C == 36000) cout << "gib u pokegomz in rel lif..\n";
    consoleUpdate(NULL);
    if (C > 36000)
{
    if (kDown & KEY_A) A++;
    if (kDown & KEY_Y) A = A+10;
    if (kDown & KEY_X) A = A+100;
    if (kDown & KEY_L) A = 1;
    if (kDown & KEY_ZL) A = 152;
    if (kDown & KEY_R) A = 252;
    if (kDown & KEY_ZR) A = 0;
    if (kDown & KEY_MINUS) A = 387;
    if (kDown & KEY_LEFT) A = 494;
    if (kDown & KEY_RIGHT) A = 650;
    if (kDown & KEY_DOWN) A = 722;
    if (kDown & KEY_UP) A = 810;
    consoleUpdate(NULL);
    if (kDown & KEY_B) 

{
        hidScanInput();

        //hidKeysDown returns information about which buttons have been just pressed (and they weren't in the previous frame)
        u32 kDown = hidKeysDown(CONTROLLER_P1_AUTO);
		if (A < 0) A = 0;
                if (A == 1) cout << "Nowe u hav a rel liv Bulbasaur!!!!!" << endl;
                if (A == 2) cout << "Nowe u hav a rel liv Ivysaur!!!!!" << endl;
                if (A == 3) cout << "Nowe u hav a rel liv Venusaur!!!!!" << endl;
                if (A == 4) cout << "Nowe u hav a rel liv Charmander!!!!!" << endl;
                if (A == 5) cout << "Nowe u hav a rel liv Charmeleon!!!!!" << endl;
                if (A == 6) cout << "Nowe u hav a rel liv Charizard!!!!!" << endl;
                if (A == 7) cout << "Nowe u hav a rel liv Squirtle!!!!!" << endl;
                if (A == 8) cout << "Nowe u hav a rel liv Wartortle!!!!!" << endl;
                if (A == 9) cout << "Nowe u hav a rel liv Blastoise!!!!!" << endl;
                if (A == 10) cout << "Nowe u hav a rel liv Caterpie!!!!!" << endl;
                if (A == 11) cout << "Nowe u hav a rel liv Metapod!!!!!" << endl;
                if (A == 12) cout << "Nowe u hav a rel liv Butterfree!!!!!" << endl;
                if (A == 13) cout << "Nowe u hav a rel liv Weedle!!!!!" << endl;
                if (A == 14) cout << "Nowe u hav a rel liv Kakuna!!!!!" << endl;
                if (A == 15) cout << "Nowe u hav a rel liv Beedrill!!!!!" << endl;
                if (A == 16) cout << "Nowe u hav a rel liv Pidgey!!!!!" << endl;
                if (A == 17) cout << "Nowe u hav a rel liv Pidgeotto!!!!!" << endl;
                if (A == 18) cout << "Nowe u hav a rel liv Pidgeot!!!!!" << endl;
                if (A == 19) cout << "Nowe u hav a rel liv Rattata!!!!!" << endl;
                if (A == 20) cout << "Nowe u hav a rel liv Raticate!!!!!" << endl;
                if (A == 21) cout << "Nowe u hav a rel liv Spearow!!!!!" << endl;
                if (A == 22) cout << "Nowe u hav a rel liv Fearow!!!!!" << endl;
                if (A == 23) cout << "Nowe u hav a rel liv Ekans!!!!!" << endl;
                if (A == 24) cout << "Nowe u hav a rel liv Arbok!!!!!" << endl;
                if (A == 25) cout << "Nowe u hav a rel liv Pikachu!!!!!" << endl;
                if (A == 26) cout << "Nowe u hav a rel liv Raichu!!!!!" << endl;
                if (A == 27) cout << "Nowe u hav a rel liv Sandshrew!!!!!" << endl;
                if (A == 28) cout << "Nowe u hav a rel liv Sandslash!!!!!" << endl;
                if (A == 29) cout << "Nowe u hav a rel liv Nidoran F!!!!!" << endl;
                if (A == 30) cout << "Nowe u hav a rel liv Nidorina!!!!!" << endl;
                if (A == 31) cout << "Nowe u hav a rel liv Nidoqueen!!!!!" << endl;
                if (A == 32) cout << "Nowe u hav a rel liv Nidoran M!!!!!" << endl;
                if (A == 33) cout << "Nowe u hav a rel liv Nidorino!!!!!" << endl;
                if (A == 34) cout << "Nowe u hav a rel liv Nidoking!!!!!" << endl;
                if (A == 35) cout << "Nowe u hav a rel liv Clefairy!!!!!" << endl;
                if (A == 36) cout << "Nowe u hav a rel liv Clefable!!!!!" << endl;
                if (A == 37) cout << "Nowe u hav a rel liv Vulpix!!!!!" << endl;
                if (A == 38) cout << "Nowe u hav a rel liv Ninetales!!!!!" << endl;
                if (A == 39) cout << "Nowe u hav a rel liv Jigglypuff!!!!!" << endl;
                if (A == 40) cout << "Nowe u hav a rel liv Wigglytuff!!!!!" << endl;
                if (A == 41) cout << "Nowe u hav a rel liv Zubat!!!!!" << endl;
                if (A == 42) cout << "Nowe u hav a rel liv Golbat!!!!!" << endl;
                if (A == 43) cout << "Nowe u hav a rel liv Oddish!!!!!" << endl;
                if (A == 44) cout << "Nowe u hav a rel liv Gloom!!!!!" << endl;
                if (A == 45) cout << "Nowe u hav a rel liv Vileplume!!!!!" << endl;
                if (A == 46) cout << "Nowe u hav a rel liv Paras!!!!!" << endl;
                if (A == 47) cout << "Nowe u hav a rel liv Parasect!!!!!" << endl;
                if (A == 48) cout << "Nowe u hav a rel liv Venonat!!!!!" << endl;
                if (A == 49) cout << "Nowe u hav a rel liv Venomoth!!!!!" << endl;
                if (A == 50) cout << "Nowe u hav a rel liv Diglett!!!!!" << endl;
                if (A == 51) cout << "Nowe u hav a rel liv Dugtrio!!!!!" << endl;
                if (A == 52) cout << "Nowe u hav a rel liv Meowth!!!!!" << endl;
                if (A == 53) cout << "Nowe u hav a rel liv Persian!!!!!" << endl;
                if (A == 54) cout << "Nowe u hav a rel liv Psyduck!!!!!" << endl;
                if (A == 55) cout << "Nowe u hav a rel liv Golduck!!!!!" << endl;
                if (A == 56) cout << "Nowe u hav a rel liv Mankey!!!!!" << endl;
                if (A == 57) cout << "Nowe u hav a rel liv Primeape!!!!!" << endl;
                if (A == 58) cout << "Nowe u hav a rel liv Growlithe!!!!!" << endl;
                if (A == 59) cout << "Nowe u hav a rel liv Arcanine!!!!!" << endl;
                if (A == 60) cout << "Nowe u hav a rel liv Poliwag!!!!!" << endl;
                if (A == 61) cout << "Nowe u hav a rel liv Poliwhirl!!!!!" << endl;
                if (A == 62) cout << "Nowe u hav a rel liv Poliwrath!!!!!" << endl;
                if (A == 63) cout << "Nowe u hav a rel liv Abra!!!!!" << endl;
                if (A == 64) cout << "Nowe u hav a rel liv Kadabra!!!!!" << endl;
                if (A == 65) cout << "Nowe u hav a rel liv Alakazam!!!!!" << endl;
                if (A == 66) cout << "Nowe u hav a rel liv Machop!!!!!" << endl;
                if (A == 67) cout << "Nowe u hav a rel liv Machoke!!!!!" << endl;
                if (A == 68) cout << "Nowe u hav a rel liv Machamp!!!!!" << endl;
                if (A == 69) cout << "Nowe u hav a rel liv Bellsprout!!!!!" << endl;
                if (A == 70) cout << "Nowe u hav a rel liv Weepinbell!!!!!" << endl;
                if (A == 71) cout << "Nowe u hav a rel liv Victreebel!!!!!" << endl;
                if (A == 72) cout << "Nowe u hav a rel liv Tentacool!!!!!" << endl;
                if (A == 73) cout << "Nowe u hav a rel liv Tentacruel!!!!!" << endl;
                if (A == 74) cout << "Nowe u hav a rel liv Geodude!!!!!" << endl;
                if (A == 75) cout << "Nowe u hav a rel liv Graveler!!!!!" << endl;
                if (A == 76) cout << "Nowe u hav a rel liv Golem!!!!!" << endl;
                if (A == 77) cout << "Nowe u hav a rel liv Ponyta!!!!!" << endl;
                if (A == 78) cout << "Nowe u hav a rel liv Rapidash!!!!!" << endl;
                if (A == 79) cout << "Nowe u hav a rel liv Slowpoke!!!!!" << endl;
                if (A == 80) cout << "Nowe u hav a rel liv Slowbro!!!!!" << endl;
                if (A == 81) cout << "Nowe u hav a rel liv Magnemite!!!!!" << endl;
                if (A == 82) cout << "Nowe u hav a rel liv Magneton!!!!!" << endl;
                if (A == 83) cout << "Nowe u hav a rel liv Farfetch'd!!!!!" << endl;
                if (A == 84) cout << "Nowe u hav a rel liv Doduo!!!!!" << endl;
                if (A == 85) cout << "Nowe u hav a rel liv Dodrio!!!!!" << endl;
                if (A == 86) cout << "Nowe u hav a rel liv Seel!!!!!" << endl;
                if (A == 87) cout << "Nowe u hav a rel liv Dewgong!!!!!" << endl;
                if (A == 88) cout << "Nowe u hav a rel liv Grimer!!!!!" << endl;
                if (A == 89) cout << "Nowe u hav a rel liv Muk!!!!!" << endl;
                if (A == 90) cout << "Nowe u hav a rel liv Shellder!!!!!" << endl;
                if (A == 91) cout << "Nowe u hav a rel liv Cloyster!!!!!" << endl;
                if (A == 92) cout << "Nowe u hav a rel liv Gastly!!!!!" << endl;
                if (A == 93) cout << "Nowe u hav a rel liv Haunter!!!!!" << endl;
                if (A == 94) cout << "Nowe u hav a rel liv Gengar!!!!!" << endl;
                if (A == 95) cout << "Nowe u hav a rel liv Onix!!!!!" << endl;
                if (A == 96) cout << "Nowe u hav a rel liv Drowzee!!!!!" << endl;
                if (A == 97) cout << "Nowe u hav a rel liv Hypno!!!!!" << endl;
                if (A == 98) cout << "Nowe u hav a rel liv Krabby!!!!!" << endl;
                if (A == 99) cout << "Nowe u hav a rel liv Kingler!!!!!" << endl;
                if (A == 100) cout << "Nowe u hav a rel liv Voltorb!!!!!" << endl;
                if (A == 101) cout << "Nowe u hav a rel liv Electrode!!!!!" << endl;
                if (A == 102) cout << "Nowe u hav a rel liv Exeggcute!!!!!" << endl;
                if (A == 103) cout << "Nowe u hav a rel liv Exeggutor!!!!!" << endl;
                if (A == 104) cout << "Nowe u hav a rel liv Cubone!!!!!" << endl;
                if (A == 105) cout << "Nowe u hav a rel liv Marowak!!!!!" << endl;
                if (A == 106) cout << "Nowe u hav a rel liv Hitmonlee!!!!!" << endl;
                if (A == 107) cout << "Nowe u hav a rel liv Hitmonchan!!!!!" << endl;
                if (A == 108) cout << "Nowe u hav a rel liv Lickitung!!!!!" << endl;
                if (A == 109) cout << "Nowe u hav a rel liv Koffing!!!!!" << endl;
                if (A == 110) cout << "Nowe u hav a rel liv Weezing!!!!!" << endl;
                if (A == 111) cout << "Nowe u hav a rel liv Rhyhorn!!!!!" << endl;
                if (A == 112) cout << "Nowe u hav a rel liv Rhydon!!!!!" << endl;
                if (A == 113) cout << "Nowe u hav a rel liv Chansey!!!!!" << endl;
                if (A == 114) cout << "Nowe u hav a rel liv Tangela!!!!!" << endl;
                if (A == 115) cout << "Nowe u hav a rel liv Kangaskhan!!!!!" << endl;
                if (A == 116) cout << "Nowe u hav a rel liv Horsea!!!!!" << endl;
                if (A == 117) cout << "Nowe u hav a rel liv Seadra!!!!!" << endl;
                if (A == 118) cout << "Nowe u hav a rel liv Goldeen!!!!!" << endl;
                if (A == 119) cout << "Nowe u hav a rel liv Seaking!!!!!" << endl;
                if (A == 120) cout << "Nowe u hav a rel liv Staryu!!!!!" << endl;
                if (A == 121) cout << "Nowe u hav a rel liv Starmie!!!!!" << endl;
                if (A == 122) cout << "Nowe u hav a rel liv Mr. Mime!!!!!" << endl;
                if (A == 123) cout << "Nowe u hav a rel liv Scyther!!!!!" << endl;
                if (A == 124) cout << "Nowe u hav a rel liv Jynx!!!!!" << endl;
                if (A == 125) cout << "Nowe u hav a rel liv Electabuzz!!!!!" << endl;
                if (A == 126) cout << "Nowe u hav a rel liv Magmar!!!!!" << endl;
                if (A == 127) cout << "Nowe u hav a rel liv Pinsir!!!!!" << endl;
                if (A == 128) cout << "Nowe u hav a rel liv Tauros!!!!!" << endl;
                if (A == 129) cout << "Nowe u hav a rel liv Magikarp!!!!!" << endl;
                if (A == 130) cout << "Nowe u hav a rel liv Gyarados!!!!!" << endl;
                if (A == 131) cout << "Nowe u hav a rel liv Lapras!!!!!" << endl;
                if (A == 132) cout << "Nowe u hav a rel liv Ditto!!!!!" << endl;
                if (A == 133) cout << "Nowe u hav a rel liv Eevee!!!!!" << endl;
                if (A == 134) cout << "Nowe u hav a rel liv Vaporeon!!!!!" << endl;
                if (A == 135) cout << "Nowe u hav a rel liv Jolteon!!!!!" << endl;
                if (A == 136) cout << "Nowe u hav a rel liv Flareon!!!!!" << endl;
                if (A == 137) cout << "Nowe u hav a rel liv Porygon!!!!!" << endl;
                if (A == 138) cout << "Nowe u hav a rel liv Omanyte!!!!!" << endl;
                if (A == 139) cout << "Nowe u hav a rel liv Omastar!!!!!" << endl;
                if (A == 140) cout << "Nowe u hav a rel liv Kabuto!!!!!" << endl;
                if (A == 141) cout << "Nowe u hav a rel liv Kabutops!!!!!" << endl;
                if (A == 142) cout << "Nowe u hav a rel liv Aerodactyl!!!!!" << endl;
                if (A == 143) cout << "Nowe u hav a rel liv Snorlax!!!!!" << endl;
                if (A == 144) cout << "Nowe u hav a rel liv Articuno!!!!!" << endl;
                if (A == 145) cout << "Nowe u hav a rel liv Zapdos!!!!!" << endl;
                if (A == 146) cout << "Nowe u hav a rel liv Moltres!!!!!" << endl;
                if (A == 147) cout << "Nowe u hav a rel liv Dratini!!!!!" << endl;
                if (A == 148) cout << "Nowe u hav a rel liv Dragonair!!!!!" << endl;
                if (A == 149) cout << "Nowe u hav a rel liv Dragonite!!!!!" << endl;
                if (A == 150) cout << "Nowe u hav a rel liv Mewtwo!!!!!" << endl;
                if (A == 151) cout << "Nowe u hav a rel liv Mew!!!!!" << endl;
                if (A == 152) cout << "Nowe u hav a rel liv Chikorita!!!!!" << endl;
                if (A == 153) cout << "Nowe u hav a rel liv Bayleef!!!!!" << endl;
                if (A == 154) cout << "Nowe u hav a rel liv Meganium!!!!!" << endl;
                if (A == 155) cout << "Nowe u hav a rel liv Cyndaquil!!!!!" << endl;
                if (A == 156) cout << "Nowe u hav a rel liv Quilava!!!!!" << endl;
                if (A == 157) cout << "Nowe u hav a rel liv Typhlosion!!!!!" << endl;
                if (A == 158) cout << "Nowe u hav a rel liv Totodile!!!!!" << endl;
                if (A == 159) cout << "Nowe u hav a rel liv Croconaw!!!!!" << endl;
                if (A == 160) cout << "Nowe u hav a rel liv Feraligatr!!!!!" << endl;
                if (A == 161) cout << "Nowe u hav a rel liv Sentret!!!!!" << endl;
                if (A == 162) cout << "Nowe u hav a rel liv Furret!!!!!" << endl;
                if (A == 163) cout << "Nowe u hav a rel liv Hoothoot!!!!!" << endl;
                if (A == 164) cout << "Nowe u hav a rel liv Noctowl!!!!!" << endl;
                if (A == 165) cout << "Nowe u hav a rel liv Ledyba!!!!!" << endl;
                if (A == 166) cout << "Nowe u hav a rel liv Ledian!!!!!" << endl;
                if (A == 167) cout << "Nowe u hav a rel liv Spinarak!!!!!" << endl;
                if (A == 168) cout << "Nowe u hav a rel liv Ariados!!!!!" << endl;
                if (A == 169) cout << "Nowe u hav a rel liv Crobat!!!!!" << endl;
                if (A == 170) cout << "Nowe u hav a rel liv Chinchou!!!!!" << endl;
                if (A == 171) cout << "Nowe u hav a rel liv Lanturn!!!!!" << endl;
                if (A == 172) cout << "Nowe u hav a rel liv Pichu!!!!!" << endl;
                if (A == 173) cout << "Nowe u hav a rel liv Cleffa!!!!!" << endl;
                if (A == 174) cout << "Nowe u hav a rel liv Igglybuff!!!!!" << endl;
                if (A == 175) cout << "Nowe u hav a rel liv Togepi!!!!!" << endl;
                if (A == 176) cout << "Nowe u hav a rel liv Togetic!!!!!" << endl;
                if (A == 177) cout << "Nowe u hav a rel liv Natu!!!!!" << endl;
                if (A == 178) cout << "Nowe u hav a rel liv Xatu!!!!!" << endl;
                if (A == 179) cout << "Nowe u hav a rel liv Mareep!!!!!" << endl;
                if (A == 180) cout << "Nowe u hav a rel liv Flaaffy!!!!!" << endl;
                if (A == 181) cout << "Nowe u hav a rel liv Ampharos!!!!!" << endl;
                if (A == 182) cout << "Nowe u hav a rel liv Bellossom!!!!!" << endl;
                if (A == 183) cout << "Nowe u hav a rel liv Marill!!!!!" << endl;
                if (A == 184) cout << "Nowe u hav a rel liv Azumarill!!!!!" << endl;
                if (A == 185) cout << "Nowe u hav a rel liv Sudowoodo!!!!!" << endl;
                if (A == 186) cout << "Nowe u hav a rel liv Politoed!!!!!" << endl;
                if (A == 187) cout << "Nowe u hav a rel liv Hoppip!!!!!" << endl;
                if (A == 188) cout << "Nowe u hav a rel liv Skiploom!!!!!" << endl;
                if (A == 189) cout << "Nowe u hav a rel liv Jumpluff!!!!!" << endl;
                if (A == 190) cout << "Nowe u hav a rel liv Aipom!!!!!" << endl;
                if (A == 191) cout << "Nowe u hav a rel liv Sunkern!!!!!" << endl;
                if (A == 192) cout << "Nowe u hav a rel liv Sunflora!!!!!" << endl;
                if (A == 193) cout << "Nowe u hav a rel liv Yanma!!!!!" << endl;
                if (A == 194) cout << "Nowe u hav a rel liv Wooper!!!!!" << endl;
                if (A == 195) cout << "Nowe u hav a rel liv Quagsire!!!!!" << endl;
                if (A == 196) cout << "Nowe u hav a rel liv Espeon!!!!!" << endl;
                if (A == 197) cout << "Nowe u hav a rel liv Umbreon!!!!!" << endl;
                if (A == 198) cout << "Nowe u hav a rel liv Murkrow!!!!!" << endl;
                if (A == 199) cout << "Nowe u hav a rel liv Slowking!!!!!" << endl;
                if (A == 200) cout << "Nowe u hav a rel liv Misdreavus!!!!!" << endl;
                if (A == 201) cout << "Nowe u hav a rel liv Unown!!!!!" << endl;
                if (A == 202) cout << "Nowe u hav a rel liv Wobbuffet!!!!!" << endl;
                if (A == 203) cout << "Nowe u hav a rel liv Girafarig!!!!!" << endl;
                if (A == 204) cout << "Nowe u hav a rel liv Pineco!!!!!" << endl;
                if (A == 205) cout << "Nowe u hav a rel liv Forretress!!!!!" << endl;
                if (A == 206) cout << "Nowe u hav a rel liv Dunsparce!!!!!" << endl;
                if (A == 207) cout << "Nowe u hav a rel liv Gligar!!!!!" << endl;
                if (A == 208) cout << "Nowe u hav a rel liv Steelix!!!!!" << endl;
                if (A == 209) cout << "Nowe u hav a rel liv Snubbull!!!!!" << endl;
                if (A == 210) cout << "Nowe u hav a rel liv Granbull!!!!!" << endl;
                if (A == 211) cout << "Nowe u hav a rel liv Qwilfish!!!!!" << endl;
                if (A == 212) cout << "Nowe u hav a rel liv Scizor!!!!!" << endl;
                if (A == 213) cout << "Nowe u hav a rel liv Shuckle!!!!!" << endl;
                if (A == 214) cout << "Nowe u hav a rel liv Heracross!!!!!" << endl;
                if (A == 215) cout << "Nowe u hav a rel liv Sneasel!!!!!" << endl;
                if (A == 216) cout << "Nowe u hav a rel liv Teddiursa!!!!!" << endl;
                if (A == 217) cout << "Nowe u hav a rel liv Ursaring!!!!!" << endl;
                if (A == 218) cout << "Nowe u hav a rel liv Slugma!!!!!" << endl;
                if (A == 219) cout << "Nowe u hav a rel liv Magcargo!!!!!" << endl;
                if (A == 220) cout << "Nowe u hav a rel liv Swinub!!!!!" << endl;
                if (A == 221) cout << "Nowe u hav a rel liv Piloswine!!!!!" << endl;
                if (A == 222) cout << "Nowe u hav a rel liv Corsola!!!!!" << endl;
                if (A == 223) cout << "Nowe u hav a rel liv Remoraid!!!!!" << endl;
                if (A == 224) cout << "Nowe u hav a rel liv Octillery!!!!!" << endl;
                if (A == 225) cout << "Nowe u hav a rel liv Delibird!!!!!" << endl;
                if (A == 226) cout << "Nowe u hav a rel liv Mantine!!!!!" << endl;
                if (A == 227) cout << "Nowe u hav a rel liv Skarmory!!!!!" << endl;
                if (A == 228) cout << "Nowe u hav a rel liv Houndour!!!!!" << endl;
                if (A == 229) cout << "Nowe u hav a rel liv Houndoom!!!!!" << endl;
                if (A == 230) cout << "Nowe u hav a rel liv Kingdra!!!!!" << endl;
                if (A == 231) cout << "Nowe u hav a rel liv Phanpy!!!!!" << endl;
                if (A == 232) cout << "Nowe u hav a rel liv Donphan!!!!!" << endl;
                if (A == 233) cout << "Nowe u hav a rel liv Porygon2!!!!!" << endl;
                if (A == 234) cout << "Nowe u hav a rel liv Stantler!!!!!" << endl;
                if (A == 235) cout << "Nowe u hav a rel liv Smeargle!!!!!" << endl;
                if (A == 236) cout << "Nowe u hav a rel liv Tyrogue!!!!!" << endl;
                if (A == 237) cout << "Nowe u hav a rel liv Hitmontop!!!!!" << endl;
                if (A == 238) cout << "Nowe u hav a rel liv Smoochum!!!!!" << endl;
                if (A == 239) cout << "Nowe u hav a rel liv Elekid!!!!!" << endl;
                if (A == 240) cout << "Nowe u hav a rel liv Magby!!!!!" << endl;
                if (A == 241) cout << "Nowe u hav a rel liv Miltank!!!!!" << endl;
                if (A == 242) cout << "Nowe u hav a rel liv Blissey!!!!!" << endl;
                if (A == 243) cout << "Nowe u hav a rel liv Raikou!!!!!" << endl;
                if (A == 244) cout << "Nowe u hav a rel liv Entei!!!!!" << endl;
                if (A == 245) cout << "Nowe u hav a rel liv Suicune!!!!!" << endl;
                if (A == 246) cout << "Nowe u hav a rel liv Larvitar!!!!!" << endl;
                if (A == 247) cout << "Nowe u hav a rel liv Pupitar!!!!!" << endl;
                if (A == 248) cout << "Nowe u hav a rel liv Tyranitar!!!!!" << endl;
                if (A == 249) cout << "Nowe u hav a rel liv Lugia!!!!!" << endl;
                if (A == 250) cout << "Nowe u hav a rel liv Ho-Oh!!!!!" << endl;
                if (A == 251) cout << "Nowe u hav a rel liv Celebi!!!!!" << endl;
                if (A == 252) cout << "Nowe u hav a rel liv Treecko!!!!!" << endl;
                if (A == 253) cout << "Nowe u hav a rel liv Grovyle!!!!!" << endl;
                if (A == 254) cout << "Nowe u hav a rel liv Sceptile!!!!!" << endl;
                if (A == 255) cout << "Nowe u hav a rel liv Torchic!!!!!" << endl;
                if (A == 256) cout << "Nowe u hav a rel liv Combusken!!!!!" << endl;
                if (A == 257) cout << "Nowe u hav a rel liv Blaziken!!!!!" << endl;
                if (A == 258) cout << "Nowe u hav a rel liv Mudkip!!!!!" << endl;
                if (A == 259) cout << "Nowe u hav a rel liv Marshtomp!!!!!" << endl;
                if (A == 260) cout << "Nowe u hav a rel liv Swampert!!!!!" << endl;
                if (A == 261) cout << "Nowe u hav a rel liv Poochyena!!!!!" << endl;
                if (A == 262) cout << "Nowe u hav a rel liv Mightyena!!!!!" << endl;
                if (A == 263) cout << "Nowe u hav a rel liv Zigzagoon!!!!!" << endl;
                if (A == 264) cout << "Nowe u hav a rel liv Linoone!!!!!" << endl;
                if (A == 265) cout << "Nowe u hav a rel liv Wurmple!!!!!" << endl;
                if (A == 266) cout << "Nowe u hav a rel liv Silcoon!!!!!" << endl;
                if (A == 267) cout << "Nowe u hav a rel liv Beautifly!!!!!" << endl;
                if (A == 268) cout << "Nowe u hav a rel liv Cascoon!!!!!" << endl;
                if (A == 269) cout << "Nowe u hav a rel liv Dustox!!!!!" << endl;
                if (A == 270) cout << "Nowe u hav a rel liv Lotad!!!!!" << endl;
                if (A == 271) cout << "Nowe u hav a rel liv Lombre!!!!!" << endl;
                if (A == 272) cout << "Nowe u hav a rel liv Ludicolo!!!!!" << endl;
                if (A == 273) cout << "Nowe u hav a rel liv Seedot!!!!!" << endl;
                if (A == 274) cout << "Nowe u hav a rel liv Nuzleaf!!!!!" << endl;
                if (A == 275) cout << "Nowe u hav a rel liv Shiftry!!!!!" << endl;
                if (A == 276) cout << "Nowe u hav a rel liv Taillow!!!!!" << endl;
                if (A == 277) cout << "Nowe u hav a rel liv Swellow!!!!!" << endl;
                if (A == 278) cout << "Nowe u hav a rel liv Wingull!!!!!" << endl;
                if (A == 279) cout << "Nowe u hav a rel liv Pelipper!!!!!" << endl;
                if (A == 280) cout << "Nowe u hav a rel liv Ralts!!!!!" << endl;
                if (A == 281) cout << "Nowe u hav a rel liv Kirlia!!!!!" << endl;
                if (A == 282) cout << "Nowe u hav a rel liv Gardevoir!!!!!" << endl;
                if (A == 283) cout << "Nowe u hav a rel liv Surskit!!!!!" << endl;
                if (A == 284) cout << "Nowe u hav a rel liv Masquerain!!!!!" << endl;
                if (A == 285) cout << "Nowe u hav a rel liv Shroomish!!!!!" << endl;
                if (A == 286) cout << "Nowe u hav a rel liv Breloom!!!!!" << endl;
                if (A == 287) cout << "Nowe u hav a rel liv Slakoth!!!!!" << endl;
                if (A == 288) cout << "Nowe u hav a rel liv Vigoroth!!!!!" << endl;
                if (A == 289) cout << "Nowe u hav a rel liv Slaking!!!!!" << endl;
                if (A == 290) cout << "Nowe u hav a rel liv Nincada!!!!!" << endl;
                if (A == 291) cout << "Nowe u hav a rel liv Ninjask!!!!!" << endl;
                if (A == 292) cout << "Nowe u hav a rel liv Shedinja!!!!!" << endl;
                if (A == 293) cout << "Nowe u hav a rel liv Whismur!!!!!" << endl;
                if (A == 294) cout << "Nowe u hav a rel liv Loudred!!!!!" << endl;
                if (A == 295) cout << "Nowe u hav a rel liv Exploud!!!!!" << endl;
                if (A == 296) cout << "Nowe u hav a rel liv Makuhita!!!!!" << endl;
                if (A == 297) cout << "Nowe u hav a rel liv Hariyama!!!!!" << endl;
                if (A == 298) cout << "Nowe u hav a rel liv Azurill!!!!!" << endl;
                if (A == 299) cout << "Nowe u hav a rel liv Nosepass!!!!!" << endl;
                if (A == 300) cout << "Nowe u hav a rel liv Skitty!!!!!" << endl;
                if (A == 301) cout << "Nowe u hav a rel liv Delcatty!!!!!" << endl;
                if (A == 302) cout << "Nowe u hav a rel liv Sableye!!!!!" << endl;
                if (A == 303) cout << "Nowe u hav a rel liv Mawile!!!!!" << endl;
                if (A == 304) cout << "Nowe u hav a rel liv Aron!!!!!" << endl;
                if (A == 305) cout << "Nowe u hav a rel liv Lairon!!!!!" << endl;
                if (A == 306) cout << "Nowe u hav a rel liv Aggron!!!!!" << endl;
                if (A == 307) cout << "Nowe u hav a rel liv Meditite!!!!!" << endl;
                if (A == 308) cout << "Nowe u hav a rel liv Medicham!!!!!" << endl;
                if (A == 309) cout << "Nowe u hav a rel liv Electrike!!!!!" << endl;
                if (A == 310) cout << "Nowe u hav a rel liv Manectric!!!!!" << endl;
                if (A == 311) cout << "Nowe u hav a rel liv Plusle!!!!!" << endl;
                if (A == 312) cout << "Nowe u hav a rel liv Minun!!!!!" << endl;
                if (A == 313) cout << "Nowe u hav a rel liv Volbeat!!!!!" << endl;
                if (A == 314) cout << "Nowe u hav a rel liv Illumise!!!!!" << endl;
                if (A == 315) cout << "Nowe u hav a rel liv Roselia!!!!!" << endl;
                if (A == 316) cout << "Nowe u hav a rel liv Gulpin!!!!!" << endl;
                if (A == 317) cout << "Nowe u hav a rel liv Swalot!!!!!" << endl;
                if (A == 318) cout << "Nowe u hav a rel liv Carvanha!!!!!" << endl;
                if (A == 319) cout << "Nowe u hav a rel liv Sharpedo!!!!!" << endl;
                if (A == 320) cout << "Nowe u hav a rel liv Wailmer!!!!!" << endl;
                if (A == 321) cout << "Nowe u hav a rel liv Wailord!!!!!" << endl;
                if (A == 322) cout << "Nowe u hav a rel liv Numel!!!!!" << endl;
                if (A == 323) cout << "Nowe u hav a rel liv Camerupt!!!!!" << endl;
                if (A == 324) cout << "Nowe u hav a rel liv Torkoal!!!!!" << endl;
                if (A == 325) cout << "Nowe u hav a rel liv Spoink!!!!!" << endl;
                if (A == 326) cout << "Nowe u hav a rel liv Grumpig!!!!!" << endl;
                if (A == 327) cout << "Nowe u hav a rel liv Spinda!!!!!" << endl;
                if (A == 328) cout << "Nowe u hav a rel liv Trapinch!!!!!" << endl;
                if (A == 329) cout << "Nowe u hav a rel liv Vibrava!!!!!" << endl;
                if (A == 330) cout << "Nowe u hav a rel liv Flygon!!!!!" << endl;
                if (A == 331) cout << "Nowe u hav a rel liv Cacnea!!!!!" << endl;
                if (A == 332) cout << "Nowe u hav a rel liv Cacturne!!!!!" << endl;
                if (A == 333) cout << "Nowe u hav a rel liv Swablu!!!!!" << endl;
                if (A == 334) cout << "Nowe u hav a rel liv Altaria!!!!!" << endl;
                if (A == 335) cout << "Nowe u hav a rel liv Zangoose!!!!!" << endl;
                if (A == 336) cout << "Nowe u hav a rel liv Seviper!!!!!" << endl;
                if (A == 337) cout << "Nowe u hav a rel liv Lunatone!!!!!" << endl;
                if (A == 338) cout << "Nowe u hav a rel liv Solrock!!!!!" << endl;
                if (A == 339) cout << "Nowe u hav a rel liv Barboach!!!!!" << endl;
                if (A == 340) cout << "Nowe u hav a rel liv Whiscash!!!!!" << endl;
                if (A == 341) cout << "Nowe u hav a rel liv Corphish!!!!!" << endl;
                if (A == 342) cout << "Nowe u hav a rel liv Crawdaunt!!!!!" << endl;
                if (A == 343) cout << "Nowe u hav a rel liv Baltoy!!!!!" << endl;
                if (A == 344) cout << "Nowe u hav a rel liv Claydol!!!!!" << endl;
                if (A == 345) cout << "Nowe u hav a rel liv Lileep!!!!!" << endl;
                if (A == 346) cout << "Nowe u hav a rel liv Cradily!!!!!" << endl;
                if (A == 347) cout << "Nowe u hav a rel liv Anorith!!!!!" << endl;
                if (A == 348) cout << "Nowe u hav a rel liv Armaldo!!!!!" << endl;
                if (A == 349) cout << "Nowe u hav a rel liv Feebas!!!!!" << endl;
                if (A == 350) cout << "Nowe u hav a rel liv Milotic!!!!!" << endl;
                if (A == 351) cout << "Nowe u hav a rel liv Castform!!!!!" << endl;
                if (A == 352) cout << "Nowe u hav a rel liv Kecleon!!!!!" << endl;
                if (A == 353) cout << "Nowe u hav a rel liv Shuppet!!!!!" << endl;
                if (A == 354) cout << "Nowe u hav a rel liv Banette!!!!!" << endl;
                if (A == 355) cout << "Nowe u hav a rel liv Duskull!!!!!" << endl;
                if (A == 356) cout << "Nowe u hav a rel liv Dusclops!!!!!" << endl;
                if (A == 357) cout << "Nowe u hav a rel liv Tropius!!!!!" << endl;
                if (A == 358) cout << "Nowe u hav a rel liv Chimecho!!!!!" << endl;
                if (A == 359) cout << "Nowe u hav a rel liv Absol!!!!!" << endl;
                if (A == 360) cout << "Nowe u hav a rel liv Wynaut!!!!!" << endl;
                if (A == 361) cout << "Nowe u hav a rel liv Snorunt!!!!!" << endl;
                if (A == 362) cout << "Nowe u hav a rel liv Glalie!!!!!" << endl;
                if (A == 363) cout << "Nowe u hav a rel liv Spheal!!!!!" << endl;
                if (A == 364) cout << "Nowe u hav a rel liv Sealeo!!!!!" << endl;
                if (A == 365) cout << "Nowe u hav a rel liv Walrein!!!!!" << endl;
                if (A == 366) cout << "Nowe u hav a rel liv Clamperl!!!!!" << endl;
                if (A == 367) cout << "Nowe u hav a rel liv Huntail!!!!!" << endl;
                if (A == 368) cout << "Nowe u hav a rel liv Gorebyss!!!!!" << endl;
                if (A == 369) cout << "Nowe u hav a rel liv Relicanth!!!!!" << endl;
                if (A == 370) cout << "Nowe u hav a rel liv Luvdisc!!!!!" << endl;
                if (A == 371) cout << "Nowe u hav a rel liv Bagon!!!!!" << endl;
                if (A == 372) cout << "Nowe u hav a rel liv Shelgon!!!!!" << endl;
                if (A == 373) cout << "Nowe u hav a rel liv Salamence!!!!!" << endl;
                if (A == 374) cout << "Nowe u hav a rel liv Beldum!!!!!" << endl;
                if (A == 375) cout << "Nowe u hav a rel liv Metang!!!!!" << endl;
                if (A == 376) cout << "Nowe u hav a rel liv Metagross!!!!!" << endl;
                if (A == 377) cout << "Nowe u hav a rel liv Regirock!!!!!" << endl;
                if (A == 378) cout << "Nowe u hav a rel liv Regice!!!!!" << endl;
                if (A == 379) cout << "Nowe u hav a rel liv Registeel!!!!!" << endl;
                if (A == 380) cout << "Nowe u hav a rel liv Latias!!!!!" << endl;
                if (A == 381) cout << "Nowe u hav a rel liv Latios!!!!!" << endl;
                if (A == 382) cout << "Nowe u hav a rel liv Kyogre!!!!!" << endl;
                if (A == 383) cout << "Nowe u hav a rel liv Groudon!!!!!" << endl;
                if (A == 384) cout << "Nowe u hav a rel liv Rayquaza!!!!!" << endl;
                if (A == 385) cout << "Nowe u hav a rel liv Jirachi!!!!!" << endl;
                if (A == 386) cout << "Nowe u hav a rel liv Deoxys!!!!!" << endl;
                if (A == 387) cout << "Nowe u hav a rel liv Turtwig!!!!!" << endl;
                if (A == 388) cout << "Nowe u hav a rel liv Grotle!!!!!" << endl;
                if (A == 389) cout << "Nowe u hav a rel liv Torterra!!!!!" << endl;
                if (A == 390) cout << "Nowe u hav a rel liv Chimchar!!!!!" << endl;
                if (A == 391) cout << "Nowe u hav a rel liv Monferno!!!!!" << endl;
                if (A == 392) cout << "Nowe u hav a rel liv Infernape!!!!!" << endl;
                if (A == 393) cout << "Nowe u hav a rel liv Piplup!!!!!" << endl;
                if (A == 394) cout << "Nowe u hav a rel liv Prinplup!!!!!" << endl;
                if (A == 395) cout << "Nowe u hav a rel liv Empoleon!!!!!" << endl;
                if (A == 396) cout << "Nowe u hav a rel liv Starly!!!!!" << endl;
                if (A == 397) cout << "Nowe u hav a rel liv Staravia!!!!!" << endl;
                if (A == 398) cout << "Nowe u hav a rel liv Staraptor!!!!!" << endl;
                if (A == 399) cout << "Nowe u hav a rel liv Bidoof!!!!!" << endl;
                if (A == 400) cout << "Nowe u hav a rel liv Bibarel!!!!!" << endl;
                if (A == 401) cout << "Nowe u hav a rel liv Kricketot!!!!!" << endl;
                if (A == 402) cout << "Nowe u hav a rel liv Kricketune!!!!!" << endl;
                if (A == 403) cout << "Nowe u hav a rel liv Shinx!!!!!" << endl;
                if (A == 404) cout << "Nowe u hav a rel liv Luxio!!!!!" << endl;
                if (A == 405) cout << "Nowe u hav a rel liv Luxray!!!!!" << endl;
                if (A == 406) cout << "Nowe u hav a rel liv Budew!!!!!" << endl;
                if (A == 407) cout << "Nowe u hav a rel liv Roserade!!!!!" << endl;
                if (A == 408) cout << "Nowe u hav a rel liv Cranidos!!!!!" << endl;
                if (A == 409) cout << "Nowe u hav a rel liv Rampardos!!!!!" << endl;
                if (A == 410) cout << "Nowe u hav a rel liv Shieldon!!!!!" << endl;
                if (A == 411) cout << "Nowe u hav a rel liv Bastiodon!!!!!" << endl;
                if (A == 412) cout << "Nowe u hav a rel liv Burmy!!!!!" << endl;
                if (A == 413) cout << "Nowe u hav a rel liv Wormadam!!!!!" << endl;
                if (A == 414) cout << "Nowe u hav a rel liv Mothim!!!!!" << endl;
                if (A == 415) cout << "Nowe u hav a rel liv Combee!!!!!" << endl;
                if (A == 416) cout << "Nowe u hav a rel liv Vespiquen!!!!!" << endl;
                if (A == 417) cout << "Nowe u hav a rel liv Pachirisu!!!!!" << endl;
                if (A == 418) cout << "Nowe u hav a rel liv Buizel!!!!!" << endl;
                if (A == 419) cout << "Nowe u hav a rel liv Floatzel!!!!!" << endl;
                if (A == 420) cout << "Nowe u hav a rel liv Cherubi!!!!!" << endl;
                if (A == 421) cout << "Nowe u hav a rel liv Cherrim!!!!!" << endl;
                if (A == 422) cout << "Nowe u hav a rel liv Shellos!!!!!" << endl;
                if (A == 423) cout << "Nowe u hav a rel liv Gastrodon!!!!!" << endl;
                if (A == 424) cout << "Nowe u hav a rel liv Ambipom!!!!!" << endl;
                if (A == 425) cout << "Nowe u hav a rel liv Drifloon!!!!!" << endl;
                if (A == 426) cout << "Nowe u hav a rel liv Drifblim!!!!!" << endl;
                if (A == 427) cout << "Nowe u hav a rel liv Buneary!!!!!" << endl;
                if (A == 428) cout << "Nowe u hav a rel liv Lopunny!!!!!" << endl;
                if (A == 429) cout << "Nowe u hav a rel liv Mismagius!!!!!" << endl;
                if (A == 430) cout << "Nowe u hav a rel liv Honchkrow!!!!!" << endl;
                if (A == 431) cout << "Nowe u hav a rel liv Glameow!!!!!" << endl;
                if (A == 432) cout << "Nowe u hav a rel liv Purugly!!!!!" << endl;
                if (A == 433) cout << "Nowe u hav a rel liv Chingling!!!!!" << endl;
                if (A == 434) cout << "Nowe u hav a rel liv Stunky!!!!!" << endl;
                if (A == 435) cout << "Nowe u hav a rel liv Skuntank!!!!!" << endl;
                if (A == 436) cout << "Nowe u hav a rel liv Bronzor!!!!!" << endl;
                if (A == 437) cout << "Nowe u hav a rel liv Bronzong!!!!!" << endl;
                if (A == 438) cout << "Nowe u hav a rel liv Bonsly!!!!!" << endl;
                if (A == 439) cout << "Nowe u hav a rel liv Mime Jr.!!!!!" << endl;
                if (A == 440) cout << "Nowe u hav a rel liv Happiny!!!!!" << endl;
                if (A == 441) cout << "Nowe u hav a rel liv Chatot!!!!!" << endl;
                if (A == 442) cout << "Nowe u hav a rel liv Spiritomb!!!!!" << endl;
                if (A == 443) cout << "Nowe u hav a rel liv Gible!!!!!" << endl;
                if (A == 444) cout << "Nowe u hav a rel liv Gabite!!!!!" << endl;
                if (A == 445) cout << "Nowe u hav a rel liv Garchomp!!!!!" << endl;
                if (A == 446) cout << "Nowe u hav a rel liv Munchlax!!!!!" << endl;
                if (A == 447) cout << "Nowe u hav a rel liv Riolu!!!!!" << endl;
                if (A == 448) cout << "Nowe u hav a rel liv Lucario!!!!!" << endl;
                if (A == 449) cout << "Nowe u hav a rel liv Hippopotas!!!!!" << endl;
                if (A == 450) cout << "Nowe u hav a rel liv Hippowdon!!!!!" << endl;
                if (A == 451) cout << "Nowe u hav a rel liv Skorupi!!!!!" << endl;
                if (A == 452) cout << "Nowe u hav a rel liv Drapion!!!!!" << endl;
                if (A == 453) cout << "Nowe u hav a rel liv Croagunk!!!!!" << endl;
                if (A == 454) cout << "Nowe u hav a rel liv Toxicroak!!!!!" << endl;
                if (A == 455) cout << "Nowe u hav a rel liv Carnivine!!!!!" << endl;
                if (A == 456) cout << "Nowe u hav a rel liv Finneon!!!!!" << endl;
                if (A == 457) cout << "Nowe u hav a rel liv Lumineon!!!!!" << endl;
                if (A == 458) cout << "Nowe u hav a rel liv Mantyke!!!!!" << endl;
                if (A == 459) cout << "Nowe u hav a rel liv Snover!!!!!" << endl;
                if (A == 460) cout << "Nowe u hav a rel liv Abomasnow!!!!!" << endl;
                if (A == 461) cout << "Nowe u hav a rel liv Weavile!!!!!" << endl;
                if (A == 462) cout << "Nowe u hav a rel liv Magnezone!!!!!" << endl;
                if (A == 463) cout << "Nowe u hav a rel liv Lickilicky!!!!!" << endl;
                if (A == 464) cout << "Nowe u hav a rel liv Rhyperior!!!!!" << endl;
                if (A == 465) cout << "Nowe u hav a rel liv Tangrowth!!!!!" << endl;
                if (A == 466) cout << "Nowe u hav a rel liv Electivire!!!!!" << endl;
                if (A == 467) cout << "Nowe u hav a rel liv Magmortar!!!!!" << endl;
                if (A == 468) cout << "Nowe u hav a rel liv Togekiss!!!!!" << endl;
                if (A == 469) cout << "Nowe u hav a rel liv Yanmega!!!!!" << endl;
                if (A == 470) cout << "Nowe u hav a rel liv Leafeon!!!!!" << endl;
                if (A == 471) cout << "Nowe u hav a rel liv Glaceon!!!!!" << endl;
                if (A == 472) cout << "Nowe u hav a rel liv Gliscor!!!!!" << endl;
                if (A == 473) cout << "Nowe u hav a rel liv Mamoswine!!!!!" << endl;
                if (A == 474) cout << "Nowe u hav a rel liv Porygon-Z!!!!!" << endl;
                if (A == 475) cout << "Nowe u hav a rel liv Gallade!!!!!" << endl;
                if (A == 476) cout << "Nowe u hav a rel liv Probopass!!!!!" << endl;
                if (A == 477) cout << "Nowe u hav a rel liv Dusknoir!!!!!" << endl;
                if (A == 478) cout << "Nowe u hav a rel liv Froslass!!!!!" << endl;
                if (A == 479) cout << "Nowe u hav a rel liv Rotom!!!!!" << endl;
                if (A == 480) cout << "Nowe u hav a rel liv Uxie!!!!!" << endl;
                if (A == 481) cout << "Nowe u hav a rel liv Mesprit!!!!!" << endl;
                if (A == 482) cout << "Nowe u hav a rel liv Azelf!!!!!" << endl;
                if (A == 483) cout << "Nowe u hav a rel liv Dialga!!!!!" << endl;
                if (A == 484) cout << "Nowe u hav a rel liv Palkia!!!!!" << endl;
                if (A == 485) cout << "Nowe u hav a rel liv Heatran!!!!!" << endl;
                if (A == 486) cout << "Nowe u hav a rel liv Regigigas!!!!!" << endl;
                if (A == 487) cout << "Nowe u hav a rel liv Giratina!!!!!" << endl;
                if (A == 488) cout << "Nowe u hav a rel liv Cresselia!!!!!" << endl;
                if (A == 489) cout << "Nowe u hav a rel liv Phione!!!!!" << endl;
                if (A == 490) cout << "Nowe u hav a rel liv Manaphy!!!!!" << endl;
                if (A == 491) cout << "Nowe u hav a rel liv Darkrai!!!!!" << endl;
                if (A == 492) cout << "Nowe u hav a rel liv Shaymin!!!!!" << endl;
                if (A == 493) cout << "Nowe u hav a rel liv Arceus!!!!!" << endl;
                if (A == 494) cout << "Nowe u hav a rel liv Victini!!!!!" << endl;
                if (A == 495) cout << "Nowe u hav a rel liv Snivy!!!!!" << endl;
                if (A == 496) cout << "Nowe u hav a rel liv Servine!!!!!" << endl;
                if (A == 497) cout << "Nowe u hav a rel liv Serperior!!!!!" << endl;
                if (A == 498) cout << "Nowe u hav a rel liv Tepig!!!!!" << endl;
                if (A == 499) cout << "Nowe u hav a rel liv Pignite!!!!!" << endl;
                if (A == 500) cout << "Nowe u hav a rel liv Emboar!!!!!" << endl;
                if (A == 501) cout << "Nowe u hav a rel liv Oshawott!!!!!" << endl;
                if (A == 502) cout << "Nowe u hav a rel liv Dewott!!!!!" << endl;
                if (A == 503) cout << "Nowe u hav a rel liv Samurott!!!!!" << endl;
                if (A == 504) cout << "Nowe u hav a rel liv Patrat!!!!!" << endl;
                if (A == 505) cout << "Nowe u hav a rel liv Watchog!!!!!" << endl;
                if (A == 506) cout << "Nowe u hav a rel liv Lillipup!!!!!" << endl;
                if (A == 507) cout << "Nowe u hav a rel liv Herdier!!!!!" << endl;
                if (A == 508) cout << "Nowe u hav a rel liv Stoutland!!!!!" << endl;
                if (A == 509) cout << "Nowe u hav a rel liv Purrloin!!!!!" << endl;
                if (A == 510) cout << "Nowe u hav a rel liv Liepard!!!!!" << endl;
                if (A == 511) cout << "Nowe u hav a rel liv Pansage!!!!!" << endl;
                if (A == 512) cout << "Nowe u hav a rel liv Simisage!!!!!" << endl;
                if (A == 513) cout << "Nowe u hav a rel liv Pansear!!!!!" << endl;
                if (A == 514) cout << "Nowe u hav a rel liv Simisear!!!!!" << endl;
                if (A == 515) cout << "Nowe u hav a rel liv Panpour!!!!!" << endl;
                if (A == 516) cout << "Nowe u hav a rel liv Simipour!!!!!" << endl;
                if (A == 517) cout << "Nowe u hav a rel liv Munna!!!!!" << endl;
                if (A == 518) cout << "Nowe u hav a rel liv Musharna!!!!!" << endl;
                if (A == 519) cout << "Nowe u hav a rel liv Pidove!!!!!" << endl;
                if (A == 520) cout << "Nowe u hav a rel liv Tranquill!!!!!" << endl;
                if (A == 521) cout << "Nowe u hav a rel liv Unfezant!!!!!" << endl;
                if (A == 522) cout << "Nowe u hav a rel liv Blitzle!!!!!" << endl;
                if (A == 523) cout << "Nowe u hav a rel liv Zebstrika!!!!!" << endl;
                if (A == 524) cout << "Nowe u hav a rel liv Roggenrola!!!!!" << endl;
                if (A == 525) cout << "Nowe u hav a rel liv Boldore!!!!!" << endl;
                if (A == 526) cout << "Nowe u hav a rel liv Gigalith!!!!!" << endl;
                if (A == 527) cout << "Nowe u hav a rel liv Woobat!!!!!" << endl;
                if (A == 528) cout << "Nowe u hav a rel liv Swoobat!!!!!" << endl;
                if (A == 529) cout << "Nowe u hav a rel liv Drilbur!!!!!" << endl;
                if (A == 530) cout << "Nowe u hav a rel liv Excadrill!!!!!" << endl;
                if (A == 531) cout << "Nowe u hav a rel liv Audino!!!!!" << endl;
                if (A == 532) cout << "Nowe u hav a rel liv Timburr!!!!!" << endl;
                if (A == 533) cout << "Nowe u hav a rel liv Gurdurr!!!!!" << endl;
                if (A == 534) cout << "Nowe u hav a rel liv Conkeldurr!!!!!" << endl;
                if (A == 535) cout << "Nowe u hav a rel liv Tympole!!!!!" << endl;
                if (A == 536) cout << "Nowe u hav a rel liv Palpitoad!!!!!" << endl;
                if (A == 537) cout << "Nowe u hav a rel liv Seismitoad!!!!!" << endl;
                if (A == 538) cout << "Nowe u hav a rel liv Throh!!!!!" << endl;
                if (A == 539) cout << "Nowe u hav a rel liv Sawk!!!!!" << endl;
                if (A == 540) cout << "Nowe u hav a rel liv Sewaddle!!!!!" << endl;
                if (A == 541) cout << "Nowe u hav a rel liv Swadloon!!!!!" << endl;
                if (A == 542) cout << "Nowe u hav a rel liv Leavanny!!!!!" << endl;
                if (A == 543) cout << "Nowe u hav a rel liv Venipede!!!!!" << endl;
                if (A == 544) cout << "Nowe u hav a rel liv Whirlipede!!!!!" << endl;
                if (A == 545) cout << "Nowe u hav a rel liv Scolipede!!!!!" << endl;
                if (A == 546) cout << "Nowe u hav a rel liv Cottonee!!!!!" << endl;
                if (A == 547) cout << "Nowe u hav a rel liv Whimsicott!!!!!" << endl;
                if (A == 548) cout << "Nowe u hav a rel liv Petilil!!!!!" << endl;
                if (A == 549) cout << "Nowe u hav a rel liv Lilligant!!!!!" << endl;
                if (A == 550) cout << "Nowe u hav a rel liv Basculin!!!!!" << endl;
                if (A == 551) cout << "Nowe u hav a rel liv Sandile!!!!!" << endl;
                if (A == 552) cout << "Nowe u hav a rel liv Krokorok!!!!!" << endl;
                if (A == 553) cout << "Nowe u hav a rel liv Krookodile!!!!!" << endl;
                if (A == 554) cout << "Nowe u hav a rel liv Darumaka!!!!!" << endl;
                if (A == 555) cout << "Nowe u hav a rel liv Darmanitan!!!!!" << endl;
                if (A == 556) cout << "Nowe u hav a rel liv Maractus!!!!!" << endl;
                if (A == 557) cout << "Nowe u hav a rel liv Dwebble!!!!!" << endl;
                if (A == 558) cout << "Nowe u hav a rel liv Crustle!!!!!" << endl;
                if (A == 559) cout << "Nowe u hav a rel liv Scraggy!!!!!" << endl;
                if (A == 560) cout << "Nowe u hav a rel liv Scrafty!!!!!" << endl;
                if (A == 561) cout << "Nowe u hav a rel liv Sigilyph!!!!!" << endl;
                if (A == 562) cout << "Nowe u hav a rel liv Yamask!!!!!" << endl;
                if (A == 563) cout << "Nowe u hav a rel liv Cofagrigus!!!!!" << endl;
                if (A == 564) cout << "Nowe u hav a rel liv Tirtouga!!!!!" << endl;
                if (A == 565) cout << "Nowe u hav a rel liv Carracosta!!!!!" << endl;
                if (A == 566) cout << "Nowe u hav a rel liv Archen!!!!!" << endl;
                if (A == 567) cout << "Nowe u hav a rel liv Archeops!!!!!" << endl;
                if (A == 568) cout << "Nowe u hav a rel liv Trubbish!!!!!" << endl;
                if (A == 569) cout << "Nowe u hav a rel liv Garbodor!!!!!" << endl;
                if (A == 570) cout << "Nowe u hav a rel liv Zorua!!!!!" << endl;
                if (A == 571) cout << "Nowe u hav a rel liv Zoroark!!!!!" << endl;
                if (A == 572) cout << "Nowe u hav a rel liv Minccino!!!!!" << endl;
                if (A == 573) cout << "Nowe u hav a rel liv Cinccino!!!!!" << endl;
                if (A == 574) cout << "Nowe u hav a rel liv Gothita!!!!!" << endl;
                if (A == 575) cout << "Nowe u hav a rel liv Gothorita!!!!!" << endl;
                if (A == 576) cout << "Nowe u hav a rel liv Gothitelle!!!!!" << endl;
                if (A == 577) cout << "Nowe u hav a rel liv Solosis!!!!!" << endl;
                if (A == 578) cout << "Nowe u hav a rel liv Duosion!!!!!" << endl;
                if (A == 579) cout << "Nowe u hav a rel liv Reuniclus!!!!!" << endl;
                if (A == 580) cout << "Nowe u hav a rel liv Ducklett!!!!!" << endl;
                if (A == 581) cout << "Nowe u hav a rel liv Swanna!!!!!" << endl;
                if (A == 582) cout << "Nowe u hav a rel liv Vanillite!!!!!" << endl;
                if (A == 583) cout << "Nowe u hav a rel liv Vanillish!!!!!" << endl;
                if (A == 584) cout << "Nowe u hav a rel liv Vanilluxe!!!!!" << endl;
                if (A == 585) cout << "Nowe u hav a rel liv Deerling!!!!!" << endl;
                if (A == 586) cout << "Nowe u hav a rel liv Sawsbuck!!!!!" << endl;
                if (A == 587) cout << "Nowe u hav a rel liv Emolga!!!!!" << endl;
                if (A == 588) cout << "Nowe u hav a rel liv Karrablast!!!!!" << endl;
                if (A == 589) cout << "Nowe u hav a rel liv Escavalier!!!!!" << endl;
                if (A == 590) cout << "Nowe u hav a rel liv Foongus!!!!!" << endl;
                if (A == 591) cout << "Nowe u hav a rel liv Amoonguss!!!!!" << endl;
                if (A == 592) cout << "Nowe u hav a rel liv Frillish!!!!!" << endl;
                if (A == 593) cout << "Nowe u hav a rel liv Jellicent!!!!!" << endl;
                if (A == 594) cout << "Nowe u hav a rel liv Alomomola!!!!!" << endl;
                if (A == 595) cout << "Nowe u hav a rel liv Joltik!!!!!" << endl;
                if (A == 596) cout << "Nowe u hav a rel liv Galvantula!!!!!" << endl;
                if (A == 597) cout << "Nowe u hav a rel liv Ferroseed!!!!!" << endl;
                if (A == 598) cout << "Nowe u hav a rel liv Ferrothorn!!!!!" << endl;
                if (A == 599) cout << "Nowe u hav a rel liv Klink!!!!!" << endl;
                if (A == 600) cout << "Nowe u hav a rel liv Klang!!!!!" << endl;
                if (A == 601) cout << "Nowe u hav a rel liv Klinklang!!!!!" << endl;
                if (A == 602) cout << "Nowe u hav a rel liv Tynamo!!!!!" << endl;
                if (A == 603) cout << "Nowe u hav a rel liv Eelektrik!!!!!" << endl;
                if (A == 604) cout << "Nowe u hav a rel liv Eelektross!!!!!" << endl;
                if (A == 605) cout << "Nowe u hav a rel liv Elgyem!!!!!" << endl;
                if (A == 606) cout << "Nowe u hav a rel liv Beheeyem!!!!!" << endl;
                if (A == 607) cout << "Nowe u hav a rel liv Litwick!!!!!" << endl;
                if (A == 608) cout << "Nowe u hav a rel liv Lampent!!!!!" << endl;
                if (A == 609) cout << "Nowe u hav a rel liv Chandelure!!!!!" << endl;
                if (A == 610) cout << "Nowe u hav a rel liv Axew!!!!!" << endl;
                if (A == 611) cout << "Nowe u hav a rel liv Fraxure!!!!!" << endl;
                if (A == 612) cout << "Nowe u hav a rel liv Haxorus!!!!!" << endl;
                if (A == 613) cout << "Nowe u hav a rel liv Cubchoo!!!!!" << endl;
                if (A == 614) cout << "Nowe u hav a rel liv Beartic!!!!!" << endl;
                if (A == 615) cout << "Nowe u hav a rel liv Cryogonal!!!!!" << endl;
                if (A == 616) cout << "Nowe u hav a rel liv Shelmet!!!!!" << endl;
                if (A == 617) cout << "Nowe u hav a rel liv Accelgor!!!!!" << endl;
                if (A == 618) cout << "Nowe u hav a rel liv Stunfisk!!!!!" << endl;
                if (A == 619) cout << "Nowe u hav a rel liv Mienfoo!!!!!" << endl;
                if (A == 620) cout << "Nowe u hav a rel liv Mienshao!!!!!" << endl;
                if (A == 621) cout << "Nowe u hav a rel liv Druddigon!!!!!" << endl;
                if (A == 622) cout << "Nowe u hav a rel liv Golett!!!!!" << endl;
                if (A == 623) cout << "Nowe u hav a rel liv Golurk!!!!!" << endl;
                if (A == 624) cout << "Nowe u hav a rel liv Pawniard!!!!!" << endl;
                if (A == 625) cout << "Nowe u hav a rel liv Bisharp!!!!!" << endl;
                if (A == 626) cout << "Nowe u hav a rel liv Bouffalant!!!!!" << endl;
                if (A == 627) cout << "Nowe u hav a rel liv Rufflet!!!!!" << endl;
                if (A == 628) cout << "Nowe u hav a rel liv Braviary!!!!!" << endl;
                if (A == 629) cout << "Nowe u hav a rel liv Vullaby!!!!!" << endl;
                if (A == 630) cout << "Nowe u hav a rel liv Mandibuzz!!!!!" << endl;
                if (A == 631) cout << "Nowe u hav a rel liv Heatmor!!!!!" << endl;
                if (A == 632) cout << "Nowe u hav a rel liv Durant!!!!!" << endl;
                if (A == 633) cout << "Nowe u hav a rel liv Deino!!!!!" << endl;
                if (A == 634) cout << "Nowe u hav a rel liv Zweilous!!!!!" << endl;
                if (A == 635) cout << "Nowe u hav a rel liv Hydreigon!!!!!" << endl;
                if (A == 636) cout << "Nowe u hav a rel liv Larvesta!!!!!" << endl;
                if (A == 637) cout << "Nowe u hav a rel liv Volcarona!!!!!" << endl;
                if (A == 638) cout << "Nowe u hav a rel liv Cobalion!!!!!" << endl;
                if (A == 639) cout << "Nowe u hav a rel liv Terrakion!!!!!" << endl;
                if (A == 640) cout << "Nowe u hav a rel liv Virizion!!!!!" << endl;
                if (A == 641) cout << "Nowe u hav a rel liv Tornadus!!!!!" << endl;
                if (A == 642) cout << "Nowe u hav a rel liv Thundurus!!!!!" << endl;
                if (A == 643) cout << "Nowe u hav a rel liv Reshiram!!!!!" << endl;
                if (A == 644) cout << "Nowe u hav a rel liv Zekrom!!!!!" << endl;
                if (A == 645) cout << "Nowe u hav a rel liv Landorus!!!!!" << endl;
                if (A == 646) cout << "Nowe u hav a rel liv Kyurem!!!!!" << endl;
                if (A == 647) cout << "Nowe u hav a rel liv Keldeo!!!!!" << endl;
                if (A == 648) cout << "Nowe u hav a rel liv Meloetta!!!!!" << endl;
                if (A == 649) cout << "Nowe u hav a rel liv Genesect!!!!!" << endl;
                if (A == 650) cout << "Nowe u hav a rel liv Chespin!!!!!" << endl;
                if (A == 651) cout << "Nowe u hav a rel liv Quilladin!!!!!" << endl;
                if (A == 652) cout << "Nowe u hav a rel liv Chesnaught!!!!!" << endl;
                if (A == 653) cout << "Nowe u hav a rel liv Fennekin!!!!!" << endl;
                if (A == 654) cout << "Nowe u hav a rel liv Braixen!!!!!" << endl;
                if (A == 655) cout << "Nowe u hav a rel liv Delphox!!!!!" << endl;
                if (A == 656) cout << "Nowe u hav a rel liv Froakie!!!!!" << endl;
                if (A == 657) cout << "Nowe u hav a rel liv Frogadier!!!!!" << endl;
                if (A == 658) cout << "Nowe u hav a rel liv Greninja!!!!!" << endl;
                if (A == 659) cout << "Nowe u hav a rel liv Bunnelby!!!!!" << endl;
                if (A == 660) cout << "Nowe u hav a rel liv Diggersby!!!!!" << endl;
                if (A == 661) cout << "Nowe u hav a rel liv Fletchling!!!!!" << endl;
                if (A == 662) cout << "Nowe u hav a rel liv Fletchinder!!!!!" << endl;
                if (A == 663) cout << "Nowe u hav a rel liv Talonflame!!!!!" << endl;
                if (A == 664) cout << "Nowe u hav a rel liv Scatterbug!!!!!" << endl;
                if (A == 665) cout << "Nowe u hav a rel liv Spewpa!!!!!" << endl;
                if (A == 666) cout << "Nowe u hav a rel liv Vivillon!!!!!" << endl;
                if (A == 667) cout << "Nowe u hav a rel liv Litleo!!!!!" << endl;
                if (A == 668) cout << "Nowe u hav a rel liv Pyroar!!!!!" << endl;
                if (A == 669) cout << "Nowe u hav a rel liv Flabébé!!!!!" << endl;
                if (A == 670) cout << "Nowe u hav a rel liv Floette!!!!!" << endl;
                if (A == 671) cout << "Nowe u hav a rel liv Florges!!!!!" << endl;
                if (A == 672) cout << "Nowe u hav a rel liv Skiddo!!!!!" << endl;
                if (A == 673) cout << "Nowe u hav a rel liv Gogoat!!!!!" << endl;
                if (A == 674) cout << "Nowe u hav a rel liv Pancham!!!!!" << endl;
                if (A == 675) cout << "Nowe u hav a rel liv Pangoro!!!!!" << endl;
                if (A == 676) cout << "Nowe u hav a rel liv Furfrou!!!!!" << endl;
                if (A == 677) cout << "Nowe u hav a rel liv Espurr!!!!!" << endl;
                if (A == 678) cout << "Nowe u hav a rel liv Meowstic!!!!!" << endl;
                if (A == 679) cout << "Nowe u hav a rel liv Honedge!!!!!" << endl;
                if (A == 680) cout << "Nowe u hav a rel liv Doublade!!!!!" << endl;
                if (A == 681) cout << "Nowe u hav a rel liv Aegislash!!!!!" << endl;
                if (A == 682) cout << "Nowe u hav a rel liv Spritzee!!!!!" << endl;
                if (A == 683) cout << "Nowe u hav a rel liv Aromatisse!!!!!" << endl;
                if (A == 684) cout << "Nowe u hav a rel liv Swirlix!!!!!" << endl;
                if (A == 685) cout << "Nowe u hav a rel liv Slurpuff!!!!!" << endl;
                if (A == 686) cout << "Nowe u hav a rel liv Inkay!!!!!" << endl;
                if (A == 687) cout << "Nowe u hav a rel liv Malamar!!!!!" << endl;
                if (A == 688) cout << "Nowe u hav a rel liv Binacle!!!!!" << endl;
                if (A == 689) cout << "Nowe u hav a rel liv Barbaracle!!!!!" << endl;
                if (A == 690) cout << "Nowe u hav a rel liv Skrelp!!!!!" << endl;
                if (A == 691) cout << "Nowe u hav a rel liv Dragalge!!!!!" << endl;
                if (A == 692) cout << "Nowe u hav a rel liv Clauncher!!!!!" << endl;
                if (A == 693) cout << "Nowe u hav a rel liv Clawitzer!!!!!" << endl;
                if (A == 694) cout << "Nowe u hav a rel liv Helioptile!!!!!" << endl;
                if (A == 695) cout << "Nowe u hav a rel liv Heliolisk!!!!!" << endl;
                if (A == 696) cout << "Nowe u hav a rel liv Tyrunt!!!!!" << endl;
                if (A == 697) cout << "Nowe u hav a rel liv Tyrantrum!!!!!" << endl;
                if (A == 698) cout << "Nowe u hav a rel liv Amaura!!!!!" << endl;
                if (A == 699) cout << "Nowe u hav a rel liv Aurorus!!!!!" << endl;
                if (A == 700) cout << "Nowe u hav a rel liv Sylveon!!!!!" << endl;
                if (A == 701) cout << "Nowe u hav a rel liv Hawlucha!!!!!" << endl;
                if (A == 702) cout << "Nowe u hav a rel liv Dedenne!!!!!" << endl;
                if (A == 703) cout << "Nowe u hav a rel liv Carbink!!!!!" << endl;
                if (A == 704) cout << "Nowe u hav a rel liv Goomy!!!!!" << endl;
                if (A == 705) cout << "Nowe u hav a rel liv Sliggoo!!!!!" << endl;
                if (A == 706) cout << "Nowe u hav a rel liv Goodra!!!!!" << endl;
                if (A == 707) cout << "Nowe u hav a rel liv Klefki!!!!!" << endl;
                if (A == 708) cout << "Nowe u hav a rel liv Phantump!!!!!" << endl;
                if (A == 709) cout << "Nowe u hav a rel liv Trevenant!!!!!" << endl;
                if (A == 710) cout << "Nowe u hav a rel liv Pumpkaboo!!!!!" << endl;
                if (A == 711) cout << "Nowe u hav a rel liv Gourgeist!!!!!" << endl;
                if (A == 712) cout << "Nowe u hav a rel liv Bergmite!!!!!" << endl;
                if (A == 713) cout << "Nowe u hav a rel liv Avalugg!!!!!" << endl;
                if (A == 714) cout << "Nowe u hav a rel liv Noibat!!!!!" << endl;
                if (A == 715) cout << "Nowe u hav a rel liv Noivern!!!!!" << endl;
                if (A == 716) cout << "Nowe u hav a rel liv Xerneas!!!!!" << endl;
                if (A == 717) cout << "Nowe u hav a rel liv Yveltal!!!!!" << endl;
                if (A == 718) cout << "Nowe u hav a rel liv Zygarde!!!!!" << endl;
                if (A == 719) cout << "Nowe u hav a rel liv Diancie!!!!!" << endl;
                if (A == 720) cout << "Nowe u hav a rel liv Hoopa!!!!!" << endl;
                if (A == 721) cout << "Nowe u hav a rel liv Volcanion!!!!!" << endl;
                if (A == 722) cout << "Nowe u hav a rel liv Rowlet!!!!!" << endl;
                if (A == 723) cout << "Nowe u hav a rel liv Dartrix!!!!!" << endl;
                if (A == 724) cout << "Nowe u hav a rel liv Decidueye!!!!!" << endl;
                if (A == 725) cout << "Nowe u hav a rel liv Litten!!!!!" << endl;
                if (A == 726) cout << "Nowe u hav a rel liv Torracat!!!!!" << endl;
                if (A == 727) cout << "Nowe u hav a rel liv Incineroar!!!!!" << endl;
                if (A == 728) cout << "Nowe u hav a rel liv Popplio!!!!!" << endl;
                if (A == 729) cout << "Nowe u hav a rel liv Brionne!!!!!" << endl;
                if (A == 730) cout << "Nowe u hav a rel liv Primarina!!!!!" << endl;
                if (A == 731) cout << "Nowe u hav a rel liv Pikipek!!!!!" << endl;
                if (A == 732) cout << "Nowe u hav a rel liv Trumbeak!!!!!" << endl;
                if (A == 733) cout << "Nowe u hav a rel liv Toucannon!!!!!" << endl;
                if (A == 734) cout << "Nowe u hav a rel liv Yungoos!!!!!" << endl;
                if (A == 735) cout << "Nowe u hav a rel liv Gumshoos!!!!!" << endl;
                if (A == 736) cout << "Nowe u hav a rel liv Grubbin!!!!!" << endl;
                if (A == 737) cout << "Nowe u hav a rel liv Charjabug!!!!!" << endl;
                if (A == 738) cout << "Nowe u hav a rel liv Vikavolt!!!!!" << endl;
                if (A == 739) cout << "Nowe u hav a rel liv Crabrawler!!!!!" << endl;
                if (A == 740) cout << "Nowe u hav a rel liv Crabominable!!!!!" << endl;
                if (A == 741) cout << "Nowe u hav a rel liv Oricorio!!!!!" << endl;
                if (A == 742) cout << "Nowe u hav a rel liv Cutiefly!!!!!" << endl;
                if (A == 743) cout << "Nowe u hav a rel liv Ribombee!!!!!" << endl;
                if (A == 744) cout << "Nowe u hav a rel liv Rockruff!!!!!" << endl;
                if (A == 745) cout << "Nowe u hav a rel liv Lycanroc!!!!!" << endl;
                if (A == 746) cout << "Nowe u hav a rel liv Wishiwashi!!!!!" << endl;
                if (A == 747) cout << "Nowe u hav a rel liv Mareanie!!!!!" << endl;
                if (A == 748) cout << "Nowe u hav a rel liv Toxapex!!!!!" << endl;
                if (A == 749) cout << "Nowe u hav a rel liv Mudbray!!!!!" << endl;
                if (A == 750) cout << "Nowe u hav a rel liv Mudsdale!!!!!" << endl;
                if (A == 751) cout << "Nowe u hav a rel liv Dewpider!!!!!" << endl;
                if (A == 752) cout << "Nowe u hav a rel liv Araquanid!!!!!" << endl;
                if (A == 753) cout << "Nowe u hav a rel liv Fomantis!!!!!" << endl;
                if (A == 754) cout << "Nowe u hav a rel liv Lurantis!!!!!" << endl;
                if (A == 755) cout << "Nowe u hav a rel liv Morelull!!!!!" << endl;
                if (A == 756) cout << "Nowe u hav a rel liv Shiinotic!!!!!" << endl;
                if (A == 757) cout << "Nowe u hav a rel liv Salandit!!!!!" << endl;
                if (A == 758) cout << "Nowe u hav a rel liv Salazzle!!!!!" << endl;
                if (A == 759) cout << "Nowe u hav a rel liv Stufful!!!!!" << endl;
                if (A == 760) cout << "Nowe u hav a rel liv Bewear!!!!!" << endl;
                if (A == 761) cout << "Nowe u hav a rel liv Bounsweet!!!!!" << endl;
                if (A == 762) cout << "Nowe u hav a rel liv Steenee!!!!!" << endl;
                if (A == 763) cout << "Nowe u hav a rel liv Tsareena!!!!!" << endl;
                if (A == 764) cout << "Nowe u hav a rel liv Comfey!!!!!" << endl;
                if (A == 765) cout << "Nowe u hav a rel liv Oranguru!!!!!" << endl;
                if (A == 766) cout << "Nowe u hav a rel liv Passimian!!!!!" << endl;
                if (A == 767) cout << "Nowe u hav a rel liv Wimpod!!!!!" << endl;
                if (A == 768) cout << "Nowe u hav a rel liv Golisopod!!!!!" << endl;
                if (A == 769) cout << "Nowe u hav a rel liv Sandygast!!!!!" << endl;
                if (A == 770) cout << "Nowe u hav a rel liv Palossand!!!!!" << endl;
                if (A == 771) cout << "Nowe u hav a rel liv Pyukumuku!!!!!" << endl;
                if (A == 772) cout << "Nowe u hav a rel liv Type: Null!!!!!" << endl;
                if (A == 773) cout << "Nowe u hav a rel liv Silvally!!!!!" << endl;
                if (A == 774) cout << "Nowe u hav a rel liv Minior!!!!!" << endl;
                if (A == 775) cout << "Nowe u hav a rel liv Komala!!!!!" << endl;
                if (A == 776) cout << "Nowe u hav a rel liv Turtonator!!!!!" << endl;
                if (A == 777) cout << "Nowe u hav a rel liv Togedemaru!!!!!" << endl;
                if (A == 778) cout << "Nowe u hav a rel liv Mimikyu!!!!!" << endl;
                if (A == 779) cout << "Nowe u hav a rel liv Bruxish!!!!!" << endl;
                if (A == 780) cout << "Nowe u hav a rel liv Drampa!!!!!" << endl;
                if (A == 781) cout << "Nowe u hav a rel liv Dhelmise!!!!!" << endl;
                if (A == 782) cout << "Nowe u hav a rel liv Jangmo-o!!!!!" << endl;
                if (A == 783) cout << "Nowe u hav a rel liv Hakamo-o!!!!!" << endl;
                if (A == 784) cout << "Nowe u hav a rel liv Kommo-o!!!!!" << endl;
                if (A == 785) cout << "Nowe u hav a rel liv Tapu Koko!!!!!" << endl;
                if (A == 786) cout << "Nowe u hav a rel liv Tapu Lele!!!!!" << endl;
                if (A == 787) cout << "Nowe u hav a rel liv Tapu Bulu!!!!!" << endl;
                if (A == 788) cout << "Nowe u hav a rel liv Tapu Fini!!!!!" << endl;
                if (A == 789) cout << "Nowe u hav a rel liv Cosmog!!!!!" << endl;
                if (A == 790) cout << "Nowe u hav a rel liv Cosmoem!!!!!" << endl;
                if (A == 791) cout << "Nowe u hav a rel liv Solgaleo!!!!!" << endl;
                if (A == 792) cout << "Nowe u hav a rel liv Lunala!!!!!" << endl;
                if (A == 793) cout << "Nowe u hav a rel liv Nihilego!!!!!" << endl;
                if (A == 794) cout << "Nowe u hav a rel liv Buzzwole!!!!!" << endl;
                if (A == 795) cout << "Nowe u hav a rel liv Pheromosa!!!!!" << endl;
                if (A == 796) cout << "Nowe u hav a rel liv Xurkitree!!!!!" << endl;
                if (A == 797) cout << "Nowe u hav a rel liv Celesteela!!!!!" << endl;
                if (A == 798) cout << "Nowe u hav a rel liv Kartana!!!!!" << endl;
                if (A == 799) cout << "Nowe u hav a rel liv Guzzlord!!!!!" << endl;
                if (A == 800) cout << "Nowe u hav a rel liv Necrozma!!!!!" << endl;
                if (A == 801) cout << "Nowe u hav a rel liv Magearna!!!!!" << endl;
                if (A == 802) cout << "Nowe u hav a rel liv Marshadow!!!!!" << endl;
                if (A == 803) cout << "Nowe u hav a rel liv Poipole!!!!!" << endl;
                if (A == 804) cout << "Nowe u hav a rel liv Naganadel!!!!!" << endl;
                if (A == 805) cout << "Nowe u hav a rel liv Stakataka!!!!!" << endl;
                if (A == 806) cout << "Nowe u hav a rel liv Blacephalon!!!!!" << endl;
                if (A == 807) cout << "Nowe u hav a rel liv Zeraora!!!!!" << endl;
                if (A == 808) cout << "Nowe u hav a rel liv Meltan!!!!!" << endl;
                if (A == 809) cout << "Nowe u hav a rel liv Melmetal!!!!!" << endl;
                if (A == 810) cout << "Nowe u hav a rel liv Grookey!!!!!" << endl;
                if (A == 811) cout << "Nowe u hav a rel liv Thwackey!!!!!" << endl;
                if (A == 812) cout << "Nowe u hav a rel liv Rillaboom!!!!!" << endl;
                if (A == 813) cout << "Nowe u hav a rel liv Scorbunny!!!!!" << endl;
                if (A == 814) cout << "Nowe u hav a rel liv Raboot!!!!!" << endl;
                if (A == 815) cout << "Nowe u hav a rel liv Cinderace!!!!!" << endl;
                if (A == 816) cout << "Nowe u hav a rel liv Sobble!!!!!" << endl;
                if (A == 817) cout << "Nowe u hav a rel liv Drizzile!!!!!" << endl;
                if (A == 818) cout << "Nowe u hav a rel liv Inteleon!!!!!" << endl;
                if (A == 819) cout << "Nowe u hav a rel liv Skwovet!!!!!" << endl;
                if (A == 820) cout << "Nowe u hav a rel liv Greedent!!!!!" << endl;
                if (A == 821) cout << "Nowe u hav a rel liv Rookidee!!!!!" << endl;
                if (A == 822) cout << "Nowe u hav a rel liv Corvisquire!!!!!" << endl;
                if (A == 823) cout << "Nowe u hav a rel liv Corviknight!!!!!" << endl;
                if (A == 824) cout << "Nowe u hav a rel liv Blipbug!!!!!" << endl;
                if (A == 825) cout << "Nowe u hav a rel liv Dottler!!!!!" << endl;
                if (A == 826) cout << "Nowe u hav a rel liv Orbeetle!!!!!" << endl;
                if (A == 827) cout << "Nowe u hav a rel liv Nickit!!!!!" << endl;
                if (A == 828) cout << "Nowe u hav a rel liv Thievul!!!!!" << endl;
                if (A == 829) cout << "Nowe u hav a rel liv Gossifleur!!!!!" << endl;
                if (A == 830) cout << "Nowe u hav a rel liv Eldegoss!!!!!" << endl;
                if (A == 831) cout << "Nowe u hav a rel liv Wooloo!!!!!" << endl;
                if (A == 832) cout << "Nowe u hav a rel liv Dubwool!!!!!" << endl;
                if (A == 833) cout << "Nowe u hav a rel liv Chewtle!!!!!" << endl;
                if (A == 834) cout << "Nowe u hav a rel liv Drednaw!!!!!" << endl;
                if (A == 835) cout << "Nowe u hav a rel liv Yamper!!!!!" << endl;
                if (A == 836) cout << "Nowe u hav a rel liv Boltund!!!!!" << endl;
                if (A == 837) cout << "Nowe u hav a rel liv Rolycoly!!!!!" << endl;
                if (A == 838) cout << "Nowe u hav a rel liv Carkol!!!!!" << endl;
                if (A == 839) cout << "Nowe u hav a rel liv Coalossal!!!!!" << endl;
                if (A == 840) cout << "Nowe u hav a rel liv Applin!!!!!" << endl;
                if (A == 841) cout << "Nowe u hav a rel liv Flapple!!!!!" << endl;
                if (A == 842) cout << "Nowe u hav a rel liv Appletun!!!!!" << endl;
                if (A == 843) cout << "Nowe u hav a rel liv Silicobra!!!!!" << endl;
                if (A == 844) cout << "Nowe u hav a rel liv Sandaconda!!!!!" << endl;
                if (A == 845) cout << "Nowe u hav a rel liv Cramorant!!!!!" << endl;
                if (A == 846) cout << "Nowe u hav a rel liv Arrokuda!!!!!" << endl;
                if (A == 847) cout << "Nowe u hav a rel liv Barraskewda!!!!!" << endl;
                if (A == 848) cout << "Nowe u hav a rel liv Toxel!!!!!" << endl;
                if (A == 849) cout << "Nowe u hav a rel liv Toxtricity!!!!!" << endl;
                if (A == 850) cout << "Nowe u hav a rel liv Sizzlipede!!!!!" << endl;
                if (A == 851) cout << "Nowe u hav a rel liv Centiskorch!!!!!" << endl;
                if (A == 852) cout << "Nowe u hav a rel liv Clobbopus!!!!!" << endl;
                if (A == 853) cout << "Nowe u hav a rel liv Grapploct!!!!!" << endl;
                if (A == 854) cout << "Nowe u hav a rel liv Sinistea!!!!!" << endl;
                if (A == 855) cout << "Nowe u hav a rel liv Polteageist!!!!!" << endl;
                if (A == 856) cout << "Nowe u hav a rel liv Hatenna!!!!!" << endl;
                if (A == 857) cout << "Nowe u hav a rel liv Hattrem!!!!!" << endl;
                if (A == 858) cout << "Nowe u hav a rel liv Hatterene!!!!!" << endl;
                if (A == 859) cout << "Nowe u hav a rel liv Impidimp!!!!!" << endl;
                if (A == 860) cout << "Nowe u hav a rel liv Morgrem!!!!!" << endl;
                if (A == 861) cout << "Nowe u hav a rel liv Grimmsnarl!!!!!" << endl;
                if (A == 862) cout << "Nowe u hav a rel liv Obstagoon!!!!!" << endl;
                if (A == 863) cout << "Nowe u hav a rel liv Perrserker!!!!!" << endl;
                if (A == 864) cout << "Nowe u hav a rel liv Cursola!!!!!" << endl;
                if (A == 865) cout << "Nowe u hav a rel liv Sirfetch'd!!!!!" << endl;
                if (A == 866) cout << "Nowe u hav a rel liv Mr. Rime!!!!!" << endl;
                if (A == 867) cout << "Nowe u hav a rel liv Runerigus!!!!!" << endl;
                if (A == 868) cout << "Nowe u hav a rel liv Milcery!!!!!" << endl;
                if (A == 869) cout << "Nowe u hav a rel liv Alcremie!!!!!" << endl;
                if (A == 870) cout << "Nowe u hav a rel liv Falinks!!!!!" << endl;
                if (A == 871) cout << "Nowe u hav a rel liv Pincurchin!!!!!" << endl;
                if (A == 872) cout << "Nowe u hav a rel liv Snom!!!!!" << endl;
                if (A == 873) cout << "Nowe u hav a rel liv Frosmoth!!!!!" << endl;
                if (A == 874) cout << "Nowe u hav a rel liv Stonjourner!!!!!" << endl;
                if (A == 875) cout << "Nowe u hav a rel liv Eiscue!!!!!" << endl;
                if (A == 876) cout << "Nowe u hav a rel liv Indeedee!!!!!" << endl;
                if (A == 877) cout << "Nowe u hav a rel liv Morpeko!!!!!" << endl;
                if (A == 878) cout << "Nowe u hav a rel liv Cufant!!!!!" << endl;
                if (A == 879) cout << "Nowe u hav a rel liv Copperajah!!!!!" << endl;
                if (A == 880) cout << "Nowe u hav a rel liv Dracozolt!!!!!" << endl;
                if (A == 881) cout << "Nowe u hav a rel liv Arctozolt!!!!!" << endl;
                if (A == 882) cout << "Nowe u hav a rel liv Dracovish!!!!!" << endl;
                if (A == 883) cout << "Nowe u hav a rel liv Arctovish!!!!!" << endl;
                if (A == 884) cout << "Nowe u hav a rel liv Duraludon!!!!!" << endl;
                if (A == 885) cout << "Nowe u hav a rel liv Dreepy!!!!!" << endl;
                if (A == 886) cout << "Nowe u hav a rel liv Drakloak!!!!!" << endl;
                if (A == 887) cout << "Nowe u hav a rel liv Dragapult!!!!!" << endl;
                if (A == 888) cout << "Nowe u hav a rel liv Zacian!!!!!" << endl;
                if (A == 889) cout << "Nowe u hav a rel liv Zamazenta!!!!!" << endl;
                if (A == 890) cout << "Nowe u hav a rel liv Eternatus!!!!!" << endl;
                if (A > 890) A = 0;
                consoleUpdate(NULL);
}

}

        if (kDown & KEY_PLUS) break; // break in order to return to hbmenu
        consoleUpdate(NULL);
}




}
    consoleExit(NULL);
    return 0;
}

